#!/usr/bin/env python3
"""Generate persistent wallpaper colors without rewriting application layouts."""
import argparse
import fcntl
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[4]
RUNTIME = ROOT / '.theme-runtime'
DISABLED = RUNTIME / 'disabled'
ROLES = {
    '1e1e2e': 'surface', '11111b': 'background', '181825': 'background',
    '313244': 'surface_container', '45475a': 'outline_variant',
    '585b70': 'outline', '555869': 'outline', '4e4e5f': 'on_surface_variant',
    '6c7086': 'on_surface_variant', '7f849c': 'on_surface_variant',
    'a6adc8': 'on_surface_variant', 'cdd6f4': 'on_surface', 'edf2f7': 'on_surface',
    '89b4fa': 'primary', '83a4e7': 'primary', 'cba6f7': 'tertiary',
    'eba0ac': 'tertiary', 'f9e2af': 'secondary', '262b3d': 'primary_container',
    '39435d': 'primary', '313a50': 'primary_container',
}
KITTY_ROLES = {
    'foreground': 'on_surface', 'background': 'background',
    'selection_foreground': 'on_primary_container', 'selection_background': 'primary_container',
    'cursor': 'primary', 'cursor_text_color': 'background',
    'active_border_color': 'primary', 'inactive_border_color': 'outline_variant',
    'active_tab_foreground': 'background', 'active_tab_background': 'primary',
    'inactive_tab_foreground': 'on_surface_variant', 'inactive_tab_background': 'surface',
    'color0': 'background', 'color8': 'outline', 'color1': 'error', 'color9': 'error',
    'color4': 'primary', 'color12': 'primary', 'color5': 'tertiary', 'color13': 'tertiary',
    'color6': 'secondary', 'color14': 'secondary', 'color7': 'on_surface', 'color15': 'on_surface',
}


def atomic(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + '.theme-tmp')
    temporary.write_text(text)
    temporary.replace(path)


def selected_wallpaper():
    state = Path(os.environ.get('XDG_STATE_HOME', str(Path.home() / '.local/state')))
    try:
        image = Path((state / 'wallpaper-selector/current').read_text().strip())
        if image.is_file():
            return image
    except OSError:
        pass
    return ROOT / 'assets/wallpapers/main.png'


def palette(image):
    key = hashlib.sha256(image.read_bytes() + b'matugen-dark-tonal-v1').hexdigest()
    cache = RUNTIME / 'palettes' / (key + '.json')
    if cache.exists():
        colors = json.loads(cache.read_text())
    else:
        executable = shutil.which('matugen')
        if not executable:
            raise RuntimeError('Install matugen: sudo pacman -S --needed matugen')
        config = RUNTIME / 'generator.toml'
        atomic(config, '[config]\n[templates]\n')
        result = subprocess.run(
            [executable, 'image', str(image), '--config', str(config), '--dry-run',
             '--mode', 'dark', '--type', 'scheme-tonal-spot', '--source-color-index', '0',
             '--old-json-output', '--json', 'hex'],
            capture_output=True, text=True, check=True, timeout=45,
        )
        raw = json.loads(result.stdout)['colors']
        colors = raw['dark'] if 'dark' in raw else {role: value['dark'] for role, value in raw.items()}
    required = set(ROLES.values()) | set(KITTY_ROLES.values())
    for role in required:
        if not re.fullmatch(r'#[0-9a-fA-F]{6}', colors[role]):
            raise RuntimeError('Invalid generated palette: ' + role)
    atomic(cache, json.dumps(colors))
    return colors


def lock_wallpaper(image):
    # Always use a PNG first frame: Hyprlock does not animate GIFs.
    import gi
    gi.require_version('GdkPixbuf', '2.0')
    from gi.repository import GdkPixbuf
    target = ROOT / 'hypr/.config/hypr/lock-wallpaper.png'
    temporary = target.with_name('lock-wallpaper.theme-tmp')
    pixbuf = GdkPixbuf.Pixbuf.new_from_file(str(image))
    pixbuf.savev(str(temporary), 'png', [], [])
    temporary.replace(target)


def outputs(colors):
    def color(hex_value):
        return colors[ROLES[hex_value]] if colors else '#' + hex_value
    css = '/* Generated by wallpaper-theme.py. */\n' + ''.join(
        f'@define-color wp_{value} {color(value)};\n' for value in ROLES)
    files = {f'{folder}/wallpaper-colors.css': css for folder in (
        'waybar/.config/waybar', 'wlogout/.config/wlogout', 'hypr/.config/hypr',
        'thunar/.config/thunar-rice')}
    files['hypr/.config/hypr/wallpaper-colors.lua'] = 'return {\n' + ''.join(
        f'    {key} = "{color(value)[1:]}",\n'
        for key, value in (('primary', '89b4fa'), ('tertiary', 'cba6f7'),
                           ('border', '45475a'), ('background', '11111b'))) + '}\n'
    files['hypr/.config/hypr/wallpaper-colors.conf'] = ''.join(
        f'$wp_{value} = rgb({color(value)[1:]})\n' for value in ROLES)
    files['kitty/.config/kitty/wallpaper-colors.conf'] = (
        '# Generated by wallpaper-theme.py.\n' + ''.join(
            f'{key} {colors[role]}\n' for key, role in KITTY_ROLES.items()) if colors
        else '# Static colors from current-theme.conf.\n')
    files['rofi/.config/rofi/wallpaper-colors.rasi'] = (
        '/* Generated by wallpaper-theme.py. */\n* {\n' + ''.join(
            f'    {name}: {value};\n' for name, value in (
                ('wp-background', color('11111b') + 'b3'),
                ('wp-surface', color('1e1e2e')),
                ('wp-foreground', color('cdd6f4')),
                ('wp-muted', color('a6adc8')),
                ('wp-accent', color('89b4fa')),
                ('wp-selection', color('262b3d')),
                ('wp-selected-text', colors['on_primary_container'] if colors else '#cdd6f4')))
        + '}\n')
    files['dunst/.config/dunst/dunstrc.d/wallpaper-colors.conf'] = (
        '# Generated by wallpaper-theme.py; layout stays in dunstrc.\n' + ''.join(
            f'[{urgency}]\n'
            f'background = "{color("1e1e2e")}"\n'
            f'foreground = "{color(foreground)}"\n'
            f'frame_color = "{frame}"\n'
            f'highlight = "{frame}"\n\n'
            for urgency, foreground, frame in (
                ('urgency_low', 'a6adc8', color('45475a')),
                ('urgency_normal', 'cdd6f4', color('89b4fa')),
                ('urgency_critical', 'cdd6f4', '#f38ba8'))))
    return files


def publish(files):
    previous = {name: (ROOT / name).read_text() if (ROOT / name).exists() else None for name in files}
    try:
        for name, text in files.items():
            atomic(ROOT / name, text)
    except Exception:
        for name, text in previous.items():
            if text is None:
                (ROOT / name).unlink(missing_ok=True)
            else:
                atomic(ROOT / name, text)
        raise


def reload_apps():
    for command in (['hyprctl', 'reload'], ['pkill', '-USR2', '-x', 'waybar'],
                    ['pkill', '-USR1', '-x', 'kitty'],
                    ['dunstctl', 'reload', str(ROOT / 'dunst/.config/dunst/dunstrc'),
                     str(ROOT / 'dunst/.config/dunst/dunstrc.d/wallpaper-colors.conf')]):
        try:
            subprocess.run(command, capture_output=True, timeout=5)
        except (OSError, subprocess.TimeoutExpired):
            print('Reload unavailable: ' + command[-1], file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('action', choices=('enable', 'apply', 'revert', 'status'))
    parser.add_argument('image', nargs='?', type=Path)
    parser.add_argument('--no-reload', action='store_true')
    args = parser.parse_args()
    RUNTIME.mkdir(exist_ok=True)
    with (RUNTIME / 'theme.lock').open('w') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        if args.action == 'status':
            print('Disabled' if DISABLED.exists() else 'Enabled')
            return
        image = (args.image or selected_wallpaper()).expanduser().resolve(strict=True)
        lock_wallpaper(image)
        if args.action == 'revert':
            publish(outputs(None))
            atomic(DISABLED, 'disabled\n')
            print('Static colors restored; automatic theming disabled.')
        else:
            colors = palette(image) if args.action == 'enable' or not DISABLED.exists() else None
            publish(outputs(colors))
            if args.action == 'enable':
                DISABLED.unlink(missing_ok=True)
            print('Wallpaper and lock-screen theme updated: ' + str(image))
        if not args.no_reload:
            reload_apps()


if __name__ == '__main__':
    try:
        main()
    except Exception as error:
        print('Wallpaper theme: ' + str(error), file=sys.stderr)
        sys.exit(1)
